name: UPB Devops 2025 CICD - Apache

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (Apache)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apache-web .

      - name: Tag image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/apache-web ${{ secrets.DOCKER_USERNAME }}/apache-web:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apache-web:latest


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub (server)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/apache-web:latest

      - name: Stop old container (if exists)
        run: docker rm -f apache-web-container || true

      - name: Run new Apache container
        run: docker run -d -p 80:80 --name apache-web-container ${{ secrets.DOCKER_USERNAME }}/apache-web:latest
